name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du projet
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests unitaires
        run: npm run test:unit

      - name: Lancer les tests d'intégration
        run: npm run test:integration

      - name: Lancer les tests e2e
        run: npm run test:e2e

      
    
    

   